# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/metered-python',
                'doc_host': 'https://metered.github.io',
                'git_url': 'https://github.com/metered/metered-python',
                'lib_path': 'metered'},
  'syms': { 'metered.auth': { 'metered.auth._capture_output': ('auth.html#_capture_output', 'metered/auth.py'),
                              'metered.auth._is_valid_token': ('auth.html#_is_valid_token', 'metered/auth.py'),
                              'metered.auth._login': ('auth.html#_login', 'metered/auth.py'),
                              'metered.auth.delete_token': ('auth.html#delete_token', 'metered/auth.py'),
                              'metered.auth.get_token': ('auth.html#get_token', 'metered/auth.py'),
                              'metered.auth.is_google_colab': ('auth.html#is_google_colab', 'metered/auth.py'),
                              'metered.auth.notebook_login': ('auth.html#notebook_login', 'metered/auth.py'),
                              'metered.auth.save_token': ('auth.html#save_token', 'metered/auth.py')},
            'metered.client': { 'metered.client.GraphQLClient': ('client.html#graphqlclient', 'metered/client.py'),
                                'metered.client.GraphQLClient.__init__': ('client.html#graphqlclient.__init__', 'metered/client.py'),
                                'metered.client.GraphQLClient.request': ('client.html#graphqlclient.request', 'metered/client.py')},
            'metered.core': {'metered.core.foo': ('core.html#foo', 'metered/core.py')}}}
